{$E+}
{$S+}

var	VAR102:integer;
	VAR104:integer;

procedure L57632; external;
procedure L57660; external;

{ Вывод статистики }
procedure L62010(
	var A:real; var B:real; var C:real; var D:real; var E:real; var F:real;
	G:integer; H:integer; I:integer; J:integer; K:integer; L:integer;
	M:integer; N:integer; O:integer; P:integer; Q:integer; R:integer);
begin
	{TODO}
end;

procedure L64564;
begin
	{TODO}
	WRITE(' :'); {L65322}
	WRITE(VAR102);
	WRITE(' ballow za');
	WRITE(VAR104);
	WRITELN(' let.');
end;

procedure L65504;
begin
	{TODO}
end;

{ Работа с KIND.DAT }
procedure L65754;
begin
	{TODO}
end;
