

	;*******************************************************
	;*                                                     *
	;*      παλετ ηςαζιώεσλιθ πςοηςανν βεκσιλ-χιμψξΰσ      *
	;*   ςαϊςαβοταξ σοτςυδξιλανι ιπι αξ σσσς ι χγλπ χηυ    *
	;*                                                     *
	;*******************************************************


	.GLOBL	CRTGRP,GRPAP,GRPEN,CLRTSP,RUSLAT
	.GLOBL	STOPEN,NOSTOP,STAND,SAND,IDIV,IV,ISV
	.GLOBL	SAVJMP,TYPE,$SCRT,ARSK,CHAR,CHRBOX,PAPER
	.GLOBL	RI,IR,SING,KOS,MLR

		GICSR =177560
		GIDBR =177562
		GRPCSR=177564
		GRPDBR=177566
		E=33

	.MACRO	.HEX	S1,S2,S3

					.ASCII	/S1/./.

		.IRPC	A,<S2>
			.IF EQ,''A-'^
					.BYTE	'4,'1
			.IFF
				.IF EQ,''A&40
					.BYTE	''A&20/20+60
				.IFF
					.BYTE	''A/20+60
				.ENDC
				.IF LE,''A&17-9.
					.BYTE	''A&17+60
				.IFF
					.BYTE	''A&17+67
				.ENDC
			.ENDC
		.ENDM
		.IRPC	B,<S3>
					.BYTE	''B
		.ENDM
	.ENDM
	;
	GRINIT::
		MOV	#INILIN,R1
	;	MOV	#ENDLIN-INILIN,R2
		CALL	ESCLN
		MOV	#4,@#$SCRT
		MOV	#8.,CHAR
		MOV	#8.,GRPEN
		MOV	#2,PAPER
		MOV	#2,GRPAP
		MOV	#2,CHRBOX
		CLR	CRTGRP
		RETURN
	;


	INILIN:
		.ASCII	<E>/%!1/
		.ASCII	<E>/[;r/
		.ASCII	<E>/P;1|/
			.HEX	<1>,<color >,<;>
			.HEX	<2>,<auto >,<;>
			.HEX	<3>,<goto >,<;>
			.HEX	<4>,<list >,<;>
			.HEX	<5>,<runM>,<;>
			.HEX	<6>,<color 8,2,2M>,<;>
			.HEX	<7>,<cload">,<;>
			.HEX	<8>,<contM>,<;>
			.HEX	<9>,<list.M[^[^>,<;>
			.HEX	<10>,<LrunM>,<>
			.BYTE	E,'/
		.ASCII	<E>/%!0/
		.ASCII	<E>/TD@@!@@!/
		.ASCII	<E>/RU@@!@@;@@3/
		.ASCII	<E>/RR `` @"oa$_@@1/
		.ASCII	<E>/ML@@7/
		.ASCII	<E>/UF `` @/
		.ASCII	<E>/MV@@0/
		.ASCII	<E>/MM@@0/
		.ASCII	<E>/LI@@7@@1@@1/
		.ASCIZ	<E>/%!3/
	ENDLIN=.
	KESC:	.ASCIZ	<E>/%!1/<E>/P1;1|/
	KENDSC:	.ASCIZ	<E>./.
	GCLS:	.ASCII	<E>/UF `` @/
		.ASCIZ	<E>/RR `` @"oa$_/
	KBDOFF: .ASCIZ	<E>/%!1/<E>/[2h/<E>/%!0/
	KBDON:	.ASCIZ	<E>/%!1/<E>/[2l/<E>/%!0/
	SET0:	.ASCII	<E>/%!1/<E>/[0;0r/
	SCR0::	.ASCIZ	<E>/%!0/
	SET3:	.ASCII	<E>/%!1/<E>/[;r/
	SCR3::	.ASCIZ	<E>/%!3/
	.EVEN
	SETSCR:	.WORD	SET3,SET0
	RETSCR:	.WORD	SCR3,SCR0
	;
	ESCLN::	MOV	R0,-(SP)
	2$:	MOVB	(1)+,R0
		BEQ	1$
		CALL	GOUT
		BR	2$
	1$:	MOV	(SP)+,R0
		RETURN
	;
	SETCRT::TST	CRTGRP
		BEQ	1$
		MOV	#SET3,R1
		CALL	ESCLN
		CLR	CRTGRP
		MOV	#14,R0
		CALL	ISV
	1$:	RETURN
	;


	KBOFF:	MOV	R1,-(SP)
		CALL	NOSTOP
		MOV	#KBDOFF,R1
		CALL	ESCLN
		MOV	#4000.,R1
	LOOP::	SOB	R1,LOOP
		MTPS	#200
		CLR	@#177560
		MTPS	#0
		MOV	(SP)+,R1
		RETURN
	;
	KBON::	MOV	R1,-(SP)
		MOV	#KBDON,R1
		CALL	ESCLN
		CALL	STOPEN
		MOV	#100,@#177560
		MOV	(SP)+,R1
		RETURN
	;
	GRPCLS::MOV	#GCLS,R1
		CALL	ESCLN
		MOV	GRPAP,R1
		DEC	R1
		CALL	GINT
		JMP	@(4)+
	;
	BEEP0::	TST	CRTGRP
		BEQ	1$
		MOV	#SCR3,R1
		CALL	ESCLN
		MOV	#7,R0
		CALL	GOUT
		MOV	#SCR0,R1
		CALL	ESCLN
		JMP	@(4)+
	1$:	MOV	#7,R0
		CALL	GOUT
		JMP	@(4)+
	;
	GCOM::;!	CALL	NOSTOP
		MOV	#33,R0		;ηςαζιώεσλαρ λοναξδα
		CALL	GOUT		;οβςαύεξιε: JSR R5,GCOM
		MOVB	(R5)+,R0	;	    .BYTE 'U,'G
		CALL	GOUT
		MOVB	(R5)+,R0
		CALL	GOUT
		RTS	R5
	;
	MIG::
		MOV	R1,-(SP)
		MOV	#SCR0,R1
		CALL	ESCLN
		MOV	(SP)+,R1
		JSR	R5,GCOM		;υσταξοχλα γχετοχ
		.BYTE	'T,'D		;νιηαξιρ λυςσοςα
		CALL	GINT		;R1 - πεςχωκ γχετ


		MOV	R2,R1		;R2 - χτοςοκ γχετ
		CALL	GINT
		MOV	CRTGRP,R1
	RET0:	MOV	RETSCR(1),R1
		CALL	ESCLN
		RETURN
	RSCR::	MOV	CRTGRP,R1
		BNE	RET0
		RETURN
	CSCR::	TST	CRTGRP
		BEQ	1$
		CALL	CRET
		MOV	#17,R1
		ADD	RUSLAT,R1
	2$:	TSTB	@#GRPCSR
		BPL	2$
		MOVB	R1,@#GRPDBR
	1$:	RETURN
	;
	GINT::	MOV	R1,-(SP)	;χωχοδ γεμοηο
		BPL	1$
		NEG	R1
	1$:	MOV	R1,R0
		ASR	R0
		ASR	R0
		SWAB	R0
		BIS	#100,R0
		CALL	GOUT
		ASR	R0
		ASR	R0
		SWAB	R0
		BIC	#177700,R0
		BIS	#100,R0
		CALL	GOUT
		MOV	R1,R0
		BIC	#177760,R0
		MOV	(SP)+,R1
		BMI	2$
		BIS	#20,R0		; +
	2$:	BIS	#40,R0
	;
	GOUT::
		TSTB	@#GRPCSR	;χωχοδ βακτα R0
		BPL	GOUT		;πο ηςαζιώεσλονυ λαξαμυ
		MOVB	R0,@#GRPDBR
		RETURN
	;
	GINP:
		TSTB	@#GICSR		;χχοδ βακτα χ R0
		BPL	GINP		;σ ηςαζιώεσλοηο λαξαμα
		MOVB	@#GIDBR,R0
		RETURN
	;
	GLNTST:	CALL	TSTXY		;ώεςώεξιε πςρνοκ δο
	GLINE:	JSR	R5,GCOM		;X=R1, Y=R2
		.BYTE	'U,'G
		BR	GXYW


	;
	GPNTST:	CALL	TSTXY		;χωχοδ τοώλι
	GPOINT:	JSR	R5,GCOM		;X=R1, Y=R2
		.BYTE	'U,'H
		BR	GXYW
	;
	GXYWT:	CALL	TSTXY
	GXYW:	ASL	R2		;χωχοδ παςω <XY> - R1,R2
		MOV	R2,R0		;HI Y
		SWAB	R0
		BIC	#177700,R0
		BIS	#40,R0
		CALL	GOUT
		MOV	R1,R0		;EXTRA
		ASL	R2
		BIC	#14,R0
		BIS	R2,R0
		BIC	#177760,R0
		BIS	#140,R0
		CALL	GOUT
		ASR	R2		;LO Y
		ASR	R2
		MOV	R2,R0
		ASR	R0
		ASR	R0
		BIC	#177740,R0
		BIS	#140,R0
		CALL	GOUT
		MOV	R1,R0		;HI X
		ASL	R0
		SWAB	R0
		BIC	#177740,R0
		BIS	#40,R0
		CALL	GOUT
		MOV	R1,R0		;LO X
		ASR	R0
		ASR	R0
		BIC	#177740,R0
		BIS	#100,R0
		CALL	GOUT
	;!	MOV	#100,@#ARSK
		RETURN
	;
	GXYST:	CALL	TSTXY		;υσταξοχλα πομοφεξιρ
	GXYS::	JSR	R5,GCOM		;ηςαζιώεσλοηο λυςσοςα
		.BYTE	'U,'F		;X=R1, Y=R2
		CALL	GXYW
		RETURN
	;
	GERROR:	TRAP	5
	;
	GXYR:
		TST	CRTGRP
		BEQ	GERROR
	GXYRD:
		CALL	KBOFF
	;	MOV	#-2,R1		;ώτεξιε πομοφεξιρ


		JSR	R5,GCOM		;ηςαζιώεσλοηο λυςσοςα
		.BYTE	'U,'I		;X=R1, Y=R2
	;	CALL	GINT
		CLR	R1
		CLR	R2
		CALL	GINP		;HI Y
		BIC	#177740,R0
		MOV	R0,R2
		SWAB	R2
		ASR	R2
		CALL	GINP		;EXTRA
		MOV	R0,R1
		BIC	#177774,R1
		BIC	#177763,R0
		ASR	R0
		ASR	R0
		BIS	R0,R2
		CALL	GINP		;LO Y
		BIC	#177740,R0
		ASL	R0
		ASL	R0
		BIS	R0,R2
		CALL	GINP		;HI X
		BIC	#177740,R0
		SWAB	R0
		ASR	R0
		BIS	R0,R1
		CALL	GINP		;LO X
		BIC	#177740,R0
		ASL	R0
		ASL	R0
		BIS	R0,R1
		CALL	GINP
		CALL	KBON
	;!	MOV	#100,@#ARSK
		RETURN
	;
	;
	$KEY::
		MOV	(SP)+,R5
		CMP	R5,#16.
		BLOS	1$
		MOV	#16.,R5
	1$:	MOV	(SP)+,R2
		MOV	(SP)+,R3
		BLE	GERROR
		CMP	R3,#20.
		BGT	GERROR
		MOV	#KESC,R1
		CALL	ESCLN
		MOV	#'0,R0
	22$:	CMP	R3,#10.
		BLT	2$
		SUB	#10.,R3
		INC	R0
		BR	22$
	2$:	CMP	R0,#'0


		BEQ	20$
		CALL	GOUT
	20$:	MOV	R3,R0
		ADD	#'0,R0
		CALL	GOUT
		MOV	#'/,R0
		CALL	GOUT
	3$:	DEC	R5
		BLT	8$
		MOVB	@R2,R0
		ASR	R0
		ASR	R0
		ASR	R0
		ASR	R0
		CMP	R0,#10.
		BGE	4$
		ADD	#'0,R0
		BR	5$
	4$:	ADD	#67,R0
	5$:	CALL	GOUT
		MOVB	(2)+,R0
		BIC	#177760,R0
		CMP	R0,#10.
		BGE	6$
		ADD	#'0,R0
		BR	7$
	6$:	ADD	#'7,R0
	7$:	CALL	GOUT
		BR	3$
	8$:	MOV	#KENDSC,R1
		CALL	ESCLN
		MOV	CRTGRP,R1
		MOV	RETSCR(1),R1
		CALL	ESCLN
		JMP	@(4)+
	;
	RETCRT::CLR	R1
		TST	CRTGRP
		BNE	S0
		JMP	@(4)+
	;
	SMODE::	MOV	(SP)+,R1
		BIC	#1,R1
		CMP	R1,#2
		BHI	GRPERR
	S0:	MOV	R1,CRTGRP
		MOV	SETSCR(1),R1
		CALL	ESCLN
		MOV	#14,R0
		CALL	ISV
		JMP	@(4)+
	;
	COLCHR::MOV	CRTGRP,R0
		MOV	CHAR(0),-(SP)
		JMP	@(4)+
	COLBOX::MOV	CHRBOX,-(SP)
		JMP	@(4)+

	COLPAP::MOV	CRTGRP,R0
		MOV	PAPER(0),-(SP)
		JMP	@(4)+
	;
	TSTXY:	CMP	R1,#640.	;λοξτςομψ πςαχιμψξοστι
		BLO	2$		;λοοςδιξατ X,Y
		BLT	1$
		MOV	#639.,R1
		BR	2$
	1$:	CLR	R1
	2$:	CMP	R2,#264.
		BLO	TSTEND
		BLT	3$
		MOV	#263.,R2
		RETURN
	3$:	CLR	R2
	TSTEND:	RETURN
	;
	TSTC3:	CMP	R3,#8.		;λοξτςομψ πςαχιμψξοστι
		BHI	COLERR		;γχετοχ
		CMP	R2,#8.
		BHI	COLERR
	TSTCOL:	CMP	R1,#8.
		BLOS	TSTEND
	;
	GRPERR:
	COLERR:	TRAP	5
	;
	COL3::	MOV	(SP)+,R3	;υσταξοχλα γχετοχ:
		MOV	(SP)+,R2	;ζοξα
		BNE	1$
		MOV	#1,R2		;0 - ώεςξωκ
	1$:	TST	R3		;ϊξαλονεστα
		BNE	2$
		MOV	R2,R3		;0 - ζοξοχωκ
	2$:	MOV	(SP)+,R1	;σινχομοχ
		BNE	3$
		MOV	R2,R1		;0 - ζοξοχωκ
	3$:	CALL	TSTC3
		MOV	R1,R5
		CALL	COLORS
		JMP	@(4)+
	;
	COLORS::
;		MOV	R1,-(SP)	; //////////
;		MOV	R2,-(SP)	; //////////
		TST	CRTGRP		; //////////
		BNE	GCOLOR		; //////////
		MOV	#SCR0,R1
		CALL	ESCLN
		JSR	R5,GCOM		;υσταξοχλα γχετοχ
		.BYTE	'L,'I
		MOV	R5,CHAR
		DEC	R5
		MOV	R5,R1
		CALL	GINT
		MOV	R3,CHRBOX
		DEC	R3
		MOV	R3,R1


		CALL	GINT
		MOV	R2,PAPER
		DEC	R2
		MOV	R2,R1
		CALL	GINT
;		MOV	(SP)+,R2	; //////////
;		MOV	(SP)+,R1	; //////////
;		TST	CRTGRP		; //////////
;		BNE	GCOLOR		; //////////
	CRET:	MOV	#SCR3,R1
		CALL	ESCLN
		RETURN
	;
	COLG::	MOV	(SP)+,R1	;υσταξοχλα γχετα ώεςώεξιρ
		BNE	C1
	CPAP::	MOV	GRPAP,R1	;ώεςτιτψ ζοξοχων
		BR	C1
	;
	CCHR::	MOV	GRPEN,R1	;ώεςτιτψ τελωύιν γχετον
	C1:	CALL	COLSET
		JMP	@(4)+
	;
	GCOLOR:	MOV	R2,GRPAP
		MOV	R1,GRPEN
		BR	GC
	;
	COLSET:	TST	CRTGRP
		BEQ	GRPERR
		CALL	TSTCOL
	GC:	DEC	R1
		JSR	R5,GCOM
		.BYTE	'M,'L
		CALL	GINT
	;!	MOV	#100,@#ARSK
		RETURN
	;
	CURCOR::CALL	GXYR
		MOV	R1,-(SP)
		MOV	R2,-(SP)
		JMP	@(R4)+
	;
	STP::	CALL	GXYR
		ADD	R1,2(SP)
		BVC	1$
		MOV	#639.,2(SP)
	1$:	ADD	R2,@SP
		BR	LSTPE
	;
	LSTP::	ADD	6(SP),2(SP)
		BVC	1$
		MOV	#639.,2(SP)
	1$:	ADD	4(SP),@SP
	LSTPE:	BVC	2$
		MOV	#263.,@SP
	2$:	JMP	@(R4)+

		BVS	GRPERR


		JMP	@(R4)+
	;
	SPFORM::
		TST	@SP
		BNE	1$
		MOV	@#GRPAP,@SP
	1$:
		JMP	@(R4)+
	SPSET::
		MOV	(SP)+,R1
		CALL	COLSET
		JMP	@(R4)+
	;
	RSP::	MOV	@#GRPEN,-(SP)
		JMP	@(R4)+
	;
	VIDSP::	MOV	@SP,-(SP)
		JMP	@(R4)+
	;

	.SBTTL	POINT	GETTING OF POINT COLOR

	;-----------------------------------------------------------------------------
	; πςογεδυςα πομυώεξιρ γχετα τοώλι, ϊαδαξξοκ λοοςδιξατω.
	; στελ ξα χθοδε:
	; 2(SP)		X-λοοςδιξατα;
	;  (SP)		Y;
	; στελ ξα χωθοδε:
	;  (SP)		λοδ γχετα τοώλι.
	;-----------------------------------------------------------------------------

	POINT::
		TST	CRTGRP
		BEQ	GRPERR		;POINT	; /////////
;		BNE	2$		; //////////
;		JMP	GRPERR		;POINT	; //////////
	2$:	MOV	(SP)+,R2	; Y
		MOV	(SP)+,R1	; X
		MOV	#-1,R0
		CMP	R1,#640.
		BHIS	1$
		CMP	R2,#264.
		BHIS	1$
		CALL	$COLOR
	1$:	MOV	R0,-(SP)	; χοϊχςαύαενωκ γχετ τοώλι
		JMP	@(R4)+
	;

	.SBTTL	SET/RESET	SPECIFIED COLOR POINT SETTING/ERASING

	;-----------------------------------------------------------------------------
	; πςογεδυςα υσταξοχλι γχετα ι ηαϋεξιρ τοώλι.
	; στελ ξα χθοδε:
	; 2(SP)		X-λοοςδιξατα;
	;  (SP)		Y;
	;-----------------------------------------------------------------------------

	SET::	MOV	(SP)+,R2
		MOV	(SP)+,R1
		CALL	GPNTST
		JMP	@(R4)+
	;

	.SBTTL	LSET	LINE'S SEGMENT DRAWING

	;-----------------------------------------------------------------------------
	; πςογεδυςα χωώεςώιχαξιρ οτςεϊλα πςρνοκ νεφδυ δχυνρ τοώλανι (X1,Y1)-(X2,Y2).
	; στελ ξα χθοδε:
	;  6(SP)	X1;
	;  4(SP)	Y1;
	;  2(SP)	X2;
	;   (SP)	Y2;
	;-----------------------------------------------------------------------------

	LSET::	MOV	6(SP),R1
		MOV	4(SP),R2
		CALL	GPNTST
		MOV	(SP)+,R2
		MOV	(SP)+,R1
		CALL	GLNTST
		CMP	(SP)+,(SP)+
		JMP	@(R4)+
	;

	.SBTTL	RECSET	RECTANGLE DRAWING

	;-----------------------------------------------------------------------------
	; πςογεδυςα οτςισοχλι πςρνουηομψξιλα σο στοςοξανι παςαμμεμψξωνι στοςοξαν
	; όλςαξα ι διαηοξαμψΰ ξα τοώλαθ (X1,Y1), (X2,Y2)
	; στελ ξα χθοδε:
	;  6(SP)	X1;
	;  4(SP)	Y1;
	;  2(SP)	X2;
	;   (SP)	Y2;
	;-----------------------------------------------------------------------------

	RECSET::MOV	@SP,R2
		MOV	2(SP),R1
		CALL	GPNTST
		MOV	6(SP),R1
		CALL	GLNTST
		MOV	4(SP),R2
		CALL	GLNTST
		MOV	2(SP),R1
		CALL	GLNTST
		MOV	(SP)+,R2
		CALL	GLNTST
		TST	(SP)+
		CMP	(SP)+,(SP)+
		JMP	@(R4)+
	;


	.SBTTL	BOXSET FILLING RECTANGLE DRAWING

	;-----------------------------------------------------------------------------
	; πςογεδυςα ςισοχαξιρ ϊαλςαϋεξξοηο πςρνουηομψξιλα σο στοςοξανι παςαμμεμψξωνι
	; στοςοξαν όλςαξα ι διαηοξαμψΰ ξα τοώλαθ (X1,Y1), (X2,Y2).
	; στελ ξα χθοδε:
	;  6(SP)	X1;
	;  4(SP)	Y1;
	;  2(SP)	X2;
	;   (SP)	Y2;
	;-----------------------------------------------------------------------------
	BOXSET::MOV	R1,R5		;υλςαστψ γχετ οτςισοχλι
		MOV	(SP)+,R2
		MOV	(SP)+,R1
		CALL	GXYST
		MOV	(SP)+,R3
		SUB	R2,R3
		BGE	1$
		ADD	R3,R2
		NEG	R3
	1$:	SUB	R1,@SP
		BGE	2$
		ADD	@SP,R1
		NEG	@SP
	2$:	JSR	R5,GCOM
		.BYTE	'R,'R
		CALL	GXYWT
		ADD	R3,R2
		ADD	(SP)+,R1
		CALL	GXYWT
		MOV	R5,R1
		CALL	GINT
		JMP	@(4)+
	;
	;
	;*****************************************************************************
	; ιπιαξ	σσσς,	οτδεμ 01,	σελτος	130
	; ηςαζιώεσλιε νοδυμι ρϊωλα BASIC.
	;*****************************************************************************

	.SBTTL	$BSCGRP	BASIC GRAPHIC

	.MACRO	PUSH	ARGS
	.IRP	ARG,<ARGS>
		MOV	ARG,-(SP)
	.ENDR
	.ENDM

	.MACRO	POP	ARGS
	.IRP	ARG,<ARGS>
		MOV	(SP)+,ARG
	.ENDR
	.ENDM


	.SBTTL	$PAINT	REGION FILLING

	;-----------------------------------------------------------------------------
	; πςογεδυςα ϊαλςασλι υλαϊαξξων γχετον οβμαστι σ ηςαξιγεκ οπςεδεμεξξοηο γχετα.
	; στελ ξα χθοδε:
	;  6(SP)	X-λοοςδιξατα τοώλι;
	;  4(SP)	Y;
	;  2(SP)	λοδ γχετα ολςασλι;
	;   (SP)	λοδ γχετα ηςαξιγω;
	; ςεηιστςω R4,R5 σοθςαξρΰτσρ.
	;-----------------------------------------------------------------------------
	$PAINT::
		MOV	(SP)+,R1
		CALL	COLSET		;υσταξοχλα γχετα ηςαξιγω
		MOV	(SP)+,R1
		DEC	R1
		NEG	R1
		JSR	R5,GCOM		;υσταξοχλα γχετα ολςασλι (ςισυξλα)
		.BYTE	'M,'P
		CALL	GINT
		MOV	(SP)+,R2
		MOV	(SP)+,R1
		CALL	GXYST		;υσταξοχλα ξαώαμψξοκ τοώλι
		JSR	R5,GCOM		;ϊαμιχλα
		.BYTE	'U,'B
		JMP	@(4)+
	;

	.SBTTL	$COLOR

	;-----------------------------------------------------------------------------
	; χξυτςεξξρρ πςογεδυςα οπςεδεμρετ γχετ ϊαδαξξοκ τοώλι.
	; ςεηιστςω ξα χθοδε:
	; R1	X-λοοςδιξατα τοώλι;
	; R2	Y.
	; ςεηιστςω ξα χωθοδε:
	; R0	γχετ τοώλι.
	; ϊα ισλμΰώεξιεν R0 ςεηιστςω σοθςαξρΰτσρ.
	;-----------------------------------------------------------------------------

	$COLOR:
		PUSH	<R1,R2>		; σοθςαξρεν ςεηιστςω
		CALL	GXYS
		CALL	KBOFF
		JSR	R5,GCOM
		.BYTE	'U,'A
		CALL	GINTR
		CALL	GINP
	;!	MOV	#100,@#ARSK
		MOV	R1,R0
		INC	R0
		CALL	KBON
		POP	<R2,R1>
		RETURN
	;
	GINTR:	CALL	GINP
		BIC	#177700,R0
		MOV	R0,R1
		SWAB	R1
		CALL	GINP
		BIC	#177700,R0
		ASL	R0
		ASL	R0
		BIS	R0,R1
		ASL	R1
		ASL	R1
		CALL	GINP
		MOV	R0,-(SP)
		BIC	#177760,R0
		BIS	R0,R1
		BIT	#20,(SP)+
		BNE	1$
		NEG	R1
	1$:	RETURN
	; υθ!!!;-----------------------------------------------------------------

	;
	ANG1::	MOV	12(SP),-(SP)
		MOV	12(SP),-(SP)
		MOV	12(SP),-(SP)
		BR	ANG
	ANG2::	MOV	16(SP),-(SP)
		MOV	16(SP),-(SP)
		MOV	16(SP),-(SP)
	ANG:	MOV	R4,-(SP)
		MOV	R4,SAVJMP
		MOV	12(SP),-(SP)
		MOV	12(SP),-(SP)
		JSR	R4,STAND
		.WORD	KOS, 2$,IR,MLR,RI,3$,4$
		.WORD	SING,5$,IR,MLR,RI,3$,6$
	2$:	MOV	6(SP),-(SP)
		JMP	@(4)+
	3$:	ADD	10(SP),@SP
		JMP	@(4)+
	4$:	MOV	14(SP),-(SP)
		MOV	14(SP),-(SP)
		BGE	8$
		NEG	4(SP)
	8$:	BIS	#100000,@SP
		JMP	@(4)+
	5$:	MOV	10(SP),-(SP)
		JMP	@(4)+
	6$:	MOV	(SP)+,12(SP)
		MOV	(SP)+,12(SP)
		MOV	(SP)+,R4
		CLR	SAVJMP
		ADD	#6,SP
		JMP	@(4)+
	ANG01::	MOV	2(SP),-(SP)
		ADD	10(SP),@SP
		MOV	6(SP),-(SP)
		JMP	@(R4)+
	ANG02::	MOV	6(SP),-(SP)
		ADD	14(SP),@SP
		MOV	12(SP),-(SP)
		JMP	@(R4)+
	ASPINT::MOV	#1,-(SP)
		JMP	@(R4)+
	ASPSNG::MOV	#1,R2
		MOV	(SP)+,R1
		BLE	7$
		CLR	R0
		BISB	R1,R0
		BIS	#200,R0
		ASL	R1
		CLRB	R1
		SWAB	R1
		SUB	#211,R1
		BGE	55$
		CMP	R1,#-20
		BLT	6$
	1$:	INC	R1

		BEQ	3$
		ASR	R0
		BCC	1$
		ROL	R0
	2$:	ASLB	R2
		BCS	4$
		INC	R1
		BNE	2$
	3$:	MOV	R0,@SP
		MOV	R2,-(SP)
		JMP	@(R4)+
	4$:	RORB	R2
		ASL	R2
	5$:	INC	R1
		BEQ	3$
		ASR	R0
		ADC	R0
		BR	5$
	55$:	MOV	#400,R0
		BR	3$
	6$:	MOV	R2,R0
		MOV	#400,R2
		BR	3$
	7$:	TRAP	5
	ASP0::	MOV	#1,-(SP)
		MOV	#1,-(SP)
		JMP	@(R4)+
	;
	$CONST:	MOV	R4,-(SP)
		MOV	R5,-(SP)
		TRAP	110
		BR	DRKL
		MOV	4(SP),R4
		MOV	R5,4(SP)
		MOV	(SP)+,R5
		RTS	R4
	DRKL:	TRAP	5
	;
	;
	$VALUE: MOV	R4,-(SP)
		MOV	R5,-(SP)
		CLR	-(SP)
		TRAP	105
		BR	9$
		BR	9$
		BR	9$
		TRAP	104
		TST	R4
		BEQ	9$
		MOV	(R4)+,@SP
		TST	TYPE
		BNE	9$
		MOV	R1,R5
		MOV	@R4,@SP
		MOV	-(R4),-(SP)
		JSR	R4,STAND
		.WORD	RI,1$

	1$:	MOV	R5,R1
	9$:	MOV	6(SP),R4
		MOV	(SP)+,4(SP)
		MOV	(SP)+,R5
		RTS	R4
	;
	$STRNG:	CLR	-(SP)
		MOV	R4,-(SP)
		MOV	R5,-(SP)
	10$:	TRAP	105
		BR	DRKL
		BR	DRKL
		BR	1$
		BR	DRKL
	1$:	TRAP	104
		TST	R4
		BEQ	5$
		MOV	6(SP),R5
		MOV	(R4)+,4(SP)
		MOV	@R4,6(SP)
		MOV	R5,R4
	4$:	MOV	(SP)+,R5
		RTS	R4
	5$:	MOV	6(SP),R4
		CLR	6(SP)
		BR	4$


	.SBTTL	$ARC	ARC DRAWING

	;-----------------------------------------------------------------------------
	; πςογεδυςα ποστςοεξιρ δυηι ολςυφξοστι ( πσεχδοόμιπσα ).
	; στελ ξα χθοδε:
	; 22(SP)	X-λοοςδιξατα γεξτςα ολςυφξοστι;
	; 20(SP)	Y;
	; 16(SP)	ςαδιυσ;
	; 14(SP)	γχετ οτςισοχλι;
	; 12(SP)	X-λοοςδιξατα ξαώαμψξοκ τοώλι;
	; 10(SP)	Y;
	;  6(SP)	X-λοοςδιξατα λοξεώξοκ τοώλι;
	;  4(SP)	Y;
	;  2(SP)	ώισμιτεμψ σοοτξοϋεξιρ λοοςδιξατ;
	;   (SP)	ϊξανεξατεμψ;
	; εσμι X-λοοςδιξατω ηςαξιώξωθ τοώελ οτςιγατεμψξωε, το πςοχοδρτσρ πςρνωε,
	; σοεδιξρΰύιε ότι τοώλι σ γεξτςον ολςυφξοστι.
	;-----------------------------------------------------------------------------
	$ARC::
		PUSH	<CHAR,R4,R5>
		MOV	R4,SAVJMP
		MOV	22(SP),R1		; λοδ γχετα
		BEQ	10$
		CALL	COLSET       		; υσταξαχμιχαεν γχετ οτςισοχλι
	10$:
		MOV	20(SP),R1		; XS < 0 ?
		BGE	12$			; ξετ
		NEG	R1
		NEG	20(SP)			; XS = -XS
		MOV	16(SP),R2		; YS
		CMP	10(SP),6(SP)		; εστψ σφατιε πο οδξοκ ιϊ οσεκ ?
		BEQ	106$			; ξετ
		BLT	103$			; δα, πο οσι Y
		SUB	30(SP),R1
		CALL	$MD
		ADD	30(SP),R1
		BR	106$
	103$:
		SUB	26(SP),R2		; σφατιε πο οσι X
		MUL	10(SP),R2
		DIV	6(SP),R2
		ADD	26(SP),R2
	106$:
		CALL	GPOINT
		MOV	30(SP),R1		; XC
		MOV	26(SP),R2		; YC
		CALL	GLINE			; ώεςτιν οτςεϊολ (XS,YS)-(XC,YC)
	12$:
		MOV	14(SP),R1		; XT < 0 ?
		BGE	14$			; ξετ
		NEG	R1
		NEG	14(SP)			; XT = -XT
		MOV	12(SP),R2		; YT
		CMP	10(SP),6(SP)
		BEQ	126$
		BLT	123$
		SUB	30(SP),R1

		CALL	$MD
		ADD	30(SP),R1
		BR	126$
	123$:
		SUB	26(SP),R2
		MUL	10(SP),R2
		DIV	6(SP),R2
		ADD	26(SP),R2
	126$:
		CALL	GPOINT
		MOV	30(SP),R1		; XC
		MOV	26(SP),R2		; YC
		CALL	GLINE			; ώεςτιν οτςεϊολ (XT,YT)-(XC,YC)
	14$:
		CLR	R1			; 0 - ξαώαμψξοε ϊξαώεξιε X-λοοςδιξατω
						; χ πεςχον λχαδςαξτε
		MOV	24(SP),R2		; R - ξαώαμψξοε ϊξαώεξιε Y-λοοςδιξατω
						; χ πεςχον λχαδςαξτε
		MOV	R2,R3			; δαμεε χωώισμρεν D[0]
		DEC	R3
		NEG	R3
		ASL	R3			; D[0]
		CMP	20(SP),14(SP)		; X-λοοςδιξατω ξαώαμψξοκ ι λοξεώξοκ
						; τοώελ δυηι σοχπαδαΰτ ?
		BNE	20$			; ξετ
		CMP	16(SP),12(SP)		; ξαώαμψξαρ ι λοξεώξαρ τοώλι
						; σοχπαδαΰτ ?
		BNE	20$			; ξετ
		MOV	#125252,R5		; ϊαδαεν οτςισοχλυ χσεκ ολςυφξοστι
		JMP	$ASET
	20$:
		SUB	30(SP),20(SP)		; πεςεθοδιν χ σιστενυ λοοςδιξατ
		SUB	26(SP),16(SP)		; σ ξαώαμον χ γεξτςε ολςυφξοστι
		SUB	30(SP),14(SP)
		SUB	26(SP),12(SP)
		CLR	R0			; R0 - ξονες λχαδςαξτα σ ( XS, YS )
		TST	20(SP)
		BGE	30$
		INC	R0
		INC	R0
		TST	16(SP)
		BLT	40$
		BR	35$

	30$:
		TST	16(SP)
		BGE	40$
	35$:
		INC	R0
	40$:
		CLR	R4			; R4 - ξονες λχαδςαξτα σ ( XT, YT )
		TST	14(SP)
		BGE	50$
		INC	R4
		INC	R4
		TST	12(SP)
		BLT	60$

		BR	55$
	50$:
		TST	12(SP)
		BGE	60$
	55$:
		INC	R4
	60$:					; "πεςεξοσιν" ξαώαμψξυΰ ι λοξεώξυΰ
		ASL	R0			; τοώλι χ 1-ωκ λχαδςαξτ
		JMP	@$QS(R0)
	$MD:
		MOV	R1,R0
		MUL	6(SP),R0
		DIV	10(SP),R0
		MOV	R0,R1
		RETURN
	$QS1:
		PUSH	<20(SP)>
		MOV	20(SP),22(SP)		; X=-Y
		NEG	22(SP)
		POP	<16(SP)>		; Y=X
		BR	$QS0
	$QS2:
		NEG	20(SP)			; X=-X
		NEG	16(SP)			; Y=-Y
		BR	$QS0
	$QS3:
		PUSH	<20(SP)>
		MOV	20(SP),22(SP)		; X=Y
		POP	<16(SP)>		; Y=-X
		NEG	16(SP)
		BR	$QS0
	$QS0:
		ASR	R0
		ASL	R4
		JMP	@$QT(R4)
	$QT1:
		PUSH	<14(SP)>
		MOV	14(SP),16(SP)
		NEG	16(SP)
		POP	<12(SP)>
		BR	$QT0
	$QT2:
		NEG	14(SP)
		NEG	12(SP)
		BR	$QT0
	$QT3:
		PUSH	<14(SP)>
		MOV	14(SP),16(SP)
		POP	<12(SP)>
		NEG	12(SP)
	$QT0:
		ASR	R4
		CLR	R5
		CMP	R0,R4			; ξαώαμψξαρ ι λοξεώξαρ τοώλι
						; χ οδξον λχαδςαξτε
		BEQ	40$			; δα
		PUSH	<#6>

		CALL	$SETCD
	10$:
		INC	R0
		CMP	#4,R0
		BNE	20$
		CLR	R0
	20$:
		CMP	R0,R4
		BEQ	30$
		PUSH	<#12>
		CALL	$SETCD
		BR	10$
	30$:
		PUSH	<#2>
		CALL	$SETCD
		BR	$ASET
	40$:
		CMP	20(SP),14(SP)		; XS-XT>0 ?
		BGT	50$
		PUSH	<#10>
		CALL	$SETCD
		BR	$ASET
	50$:
		MOV	#125252,R5	;?
		PUSH	<#4>
		CALL	$SETCD
	$ASET:
		CALL	$P4SET
		TST	R5			; ποστςοεξα χσρ δυηα ?
		BEQ	$AEND			; δα
		MOV	R3,R0			; D[I]
		BGT	20$
	;------ D[I] <= 0
		ADD	R2,R0			; χωώισμρεν L[I]
		ASL	R0
		DEC	R0
		BGT	10$
	;...... D[I] <= 0 AND L[I] <= 0   ===> M1
		INC	R1			; X[I+1]=X[I]+1
		MOV	R1,R0
		ASL	R0
		ADD	R0,R3
		INC	R3			; D[I+1]=D[I]+2*X[I+1]+1
		BR	$ASET
	;...... D[I] <= 0 AND L[I] > 0 OR D[I] >= 0 AND L'[I] <= 0 ====> M2
	10$:
		INC	R1			; X[I+1]=X[I]+1
		DEC	R2			; Y[I+1]=Y[I]-1
		MOV	R1,R0
		SUB	R2,R0
		INC	R0
		ASL	R0
		ADD	R0,R3			; D[I+1]=D[I]+2*X[I+1]-2*Y[I+1]+2
		BR	$ASET
	;------ D[I] > 0
	20$:
		SUB	R1,R0			; χωώισμρεν L'[I]

		ASL	R0
		DEC	R0
		BLE	10$
	;...... D[I] > 0 AND L'[I] > 0
		DEC	R2			; Y[I+1]=Y[I]-1
		MOV	R2,R0
		ASL	R0
		SUB	R0,R3
		INC	R3
		BR	$ASET
	$AEND:
		POP	<R5,R4,R3>
		ADD	#20,SP
		POP	<R2,R1>
		CALL	GXYST
		CLR	SAVJMP
		JMP	@(4)+
	$QS:
		.WORD	$QS0
		.WORD	$QS1
		.WORD	$QS2
		.WORD	$QS3
	$QT:
		.WORD	$QT0
		.WORD	$QT1
		.WORD	$QT2
		.WORD	$QT3


	.SBTTL	$SETCD	QUADRANT CODE SETTING

	;-----------------------------------------------------------------------------
	; χξυτςεξξρρ πςογεδυςα οπςεδεμεξιρ λοδα λχαδςαξτα.
	; στελ ξα χθοδε:
	; 2(SP)		υσταξαχμιχαενωκ λοδ;
	;  (SP)		αδςεσ χοϊχςατα.
	;-----------------------------------------------------------------------------

	$SETCD:
		PUSH	<R0,R1,R2>
		MOV	10(SP),R1		; υσταξαχμιχαενωκ λοδ
		MOV	#17,R2			; νασλα
		TST	R0
		BEQ	20$
	10$:
		ASL	R1
		ASL	R1
		ASL	R1
		ASL	R1
		ASL	R2
		ASL	R2
		ASL	R2
		ASL	R2
		SOB	R0,10$
	20$:
		BIC	R2,R5
		BIS	R1,R5
		POP	<R2,R1,R0,(SP)>
		RETURN


	.SBTTL	$P4SET	SYMMETRICAL POINTS CHECKING AND DRAWING

	;-----------------------------------------------------------------------------
	; χξυτςεξξρρ πςογεδυςα πςοχεςλι δοπυστινοστι ι οτςισοχλι 4-θ σιννετςιώξωθ
	; τοώελ.
	; χθοδξωε παςανετςω:
	; R1	οτξοσιτεμψξαρ X-λοοςδιξατα τοώλι ( χ 1-ον λχαδςαξτε );
	; R2	Y;
	; R5	λοδ λχαδςαξτα.
	; χωθοδξωε παςανετςω:
	; R5	λοδ λχαδςαξτα.
	; ξε σοθςαξρετσρ R0.
	; χξιναξιε!!! σιρ πςογεδυςα ξαημο ισπομψϊυετ ϊξαξιε στελα, ποότονυ μΰβωε
	; ισπςαχμεξιρ χ χωϊωχαΰύεκ πςογεδυςε $ARC, ϊατςαηιχαΰύιε στελ πςιχεδυτ
	; λ ξεοβθοδινοστι εε λοςςελγιι.
	;-----------------------------------------------------------------------------

	$P4SET:
		PUSH	<R5,R5>
		CLR	R0			; ξονες λχαδςαξτα ( 0,1,2,3 )
	$P4CYC:
		BIC	#177760,R5		; χωδεμρεν λοδ οώεςεδξοηο λχαδςαξτα
		JMP	@$CODE(R5)		; οβςαβατωχαεν τοώλυ χ χωδεμεξξον
						; λχαδςαξτε σοημασξο εε λοδυ

	$C0000:					; δυηα χ λχαδςαξτε ξε χωώεςώιχαετσρ
		INC	R0
		CMP	#4,R0			; οβςαβοταξω χσε λχαδςαξτω ?
		BNE	10$
		JMP	$P4END			; δα
	10$:
		POP	<R5>
		ASR	R5
		ASR	R5
		ASR	R5
		ASR	R5
		PUSH	<R5>
		BR	$P4CYC
	$C0010:					; δυηα χωώεςώιχαετσρ οτ ξαώαμα
						; λχαδςαξτα δο λοξεώξοκ τοώλι
		CMP	R1,22(SP)		; δοστιηξυτα λοξεώξαρ τοώλα ?
		BLT	$L2			; ξετ
		CMP	R2,20(SP)
		BGT	$L2
		CLR	R5			; υσταξαχμιχαεν, ώτο χ οσταχϋεκσρ
						; ώαστι λχαδςαξτα δυηα ξε χωώεςώι-
						; χαετσρ
	$L0:					; δαμεε σμεδυετ υσταξοχλα λοδα
						; χωώεςώιχαενοστι δυηι χ δαξξον
						; λχαδςαξτε
		MOV	#17,R4			; νασλα
		PUSH	<R0>			; σοθςαξρεν ξονες λχαδςαξτα
		BEQ	$L1
	10$:
		ASL	R5
		ASL	R5
		ASL	R5

		ASL	R5
		ASL	R4
		ASL	R4
		ASL	R4
		ASL	R4
		SOB	R0,10$
	$L1:
		POP	<R0>			; χοσσταξαχμιχαεν ξονες λχαδςαξτα
		BIC	R4,2(SP)		; ηασιν πςεδωδυύικ λοδ
		BIS	R5,2(SP)		; υσταξαχμιχαεν ξοχωκ
	$L2:					; οτςισοχλα τοώλι
		PUSH	<R0,R1,R2>
		ASL	R0
		JMP	@$QUA(R0)
	$Q0:
		PUSH	<R3>
		CMP	26(SP),24(SP)
		BEQ	$L8
		BLT	$L5
		MOV	R1,R0
		MUL	24(SP),R0
		DIV	26(SP),R0
		MOV	R0,R1
		BR	$L8
	$L5:
		MUL	26(SP),R2
		DIV	24(SP),R2
	$L8:
		POP	<R3>
		ADD	44(SP),R1
		ADD	42(SP),R2
		CALL	GPOINT			; χωχοδιν τοώλυ
		POP	<R2,R1,R0>
		BR	$C0000
	$Q1:
		MOV	R2,R1			; X=Y
		MOV	2(SP),R2		; Y=-X
		NEG	R2
		BR	$Q0
	$Q2:
		NEG	R1			; X=-X
		NEG	R2			; Y=-Y
		BR	$Q0
	$Q3:
		MOV	R2,R1			; X=-Y
		NEG	R1
		MOV	2(SP),R2		; Y=X
		BR	$Q0
	$C0100:					; δυηα χωώεςώιχαετσρ οτ ξαώαμα
						; λχαδςαξτα δο λοξεώξοκ τοώλι ι
						; οτ ξαώαμψξοκ τοώλι δο λοξγα
						; λχαδςαξτα
		CMP	R1,22(SP)		; λοξεώξαρ τοώλα δοστιηξυτα ?
		BLT	$L2			; ξετ
		CMP	R2,20(SP)
		BGT	$L2
		MOV	#6,R5			; υσταξαχμιχαεν πςιϊξαλ οτςισοχλι

						; οτ ξαώαμψξοκ τοώλι δο λοξγα
						; λχαδςαξτα
		BR	$L0
	$C0110:					; δυηα χωώεςώιχαετσρ οτ ξαώαμψξοκ
						; τοώλι δο λοξγα λχαδςαξτα
		CMP	R1,26(SP)		; ξαώαμψξαρ τοώλα δοστιηξυτα ?
		BLT	$C0000			; ξετ
		CMP	R2,24(SP)
		BGT	$C0000
		MOV	#12,R5			; υσταξαχμιχαεν πςιϊξαλ οτςισοχλι
						; χσεηο ( οσταχϋεηοσρ) λχαδςαξτα
		BR	$L0
	$C1000:					; δυηα χωώεςώιχαετσρ χ πςεδεμαθ
						; οδξοηο λχαδςαξτα οτ ξαώαμψξοκ
						; δο λοξεώξοκ τοώλι
		CMP	R1,26(SP)		; ξαώαμψξαρ τοώλα δοστιηξυτα ?
		BGE	5$
		JMP	$C0000			; ξετ
	5$:
		CMP	R2,24(SP)
		BLE	10$
		JMP	$C0000
	10$:
		MOV	#2,R5			; υσταξαχμιχαεν πςιϊξαλ οτςισοχλι
						; οτ ξαώαμα λχαδςαξτα δο λοξεώξοκ
						; τοώλι
		BR	$L0
	$C1010:					; δυηα ώεςτιτσρ χο χσεν λχαδςαξτε
		CMP	R1,32(SP)		; δοστιηξυτ λοξεγ λχαδςαξτα ?
		BLT	$L2			; ξετ
		TST	R2
		BGT	$L2
		CLR	R5
		BR	$L0
	$P4END:
		POP	<R5,R5>
		RETURN
	$CODE:
		.WORD	$C0000
		.WORD	$C0010
		.WORD	$C0100
		.WORD	$C0110
		.WORD	$C1000
		.WORD	$C1010
	$QUA:
		.WORD	$Q0
		.WORD	$Q1
		.WORD	$Q2
		.WORD	$Q3
	; υθ!!!
	.MACRO	PUSH	ARGS		; PUSH:  αςη-->στελ
	.IRP	ARG,<ARGS>
		MOV	ARG,-(SP)
	.ENDR
	.ENDM
	.MACRO	POP	ARGS		; POP:   στελ-->αςη
	.IRP	ARG,<ARGS>

		MOV	(SP)+,ARG
	.ENDR
	.ENDM
	;************************************************
	;		πςοηςανα  οπεςατοςα DRAW
	;	ξα χθοδε:	χ στελε 2(SP) -αδςεσ στςολι
	;				 (SP) -δμιξα στςολι
	;	ξα χωθοδε:	στελ πυστ
	;	χσε ςεηιστςω σοθςαξΰτσρ.
	;	πςι χωϊοχαθ $CONST,$VALUE,$STRNG R4 σοθς.
	;************************************************
	;
	$DRAW::
		MOV	R4,SAVJMP
		CALL	CLRTSP
		POP	<R5,R3>		; ιϊχμεώψ δμ. ι αδς.στς
		BEQ	OUT
		CALL	GXYR		; ξαώαμψξοε πομοφεξιε
		MOV	R5,R0		; σοθςαξιτψ
		PUSH	<R0,CHAR>	; σοθς. R5,γχετ
		CLR	-(SP)		; ϊαπισψ σμοχ( 0,0 -πςιϊξαλ ολοξώαξιρ ),
		CLR	-(SP)
		MOV	#70000,-(SP)	; ι σμοχα πεςενεύεξικ  ( WM )( 70000 )
	NEWSTR:
		TST	R3		; ξυμεχοκ αδςεσ-πςιϊξαλ λοξγα ?
		BEQ	OUT		; δα--χωθοδ ιϊ  $DRAW
		ADD	R3,R5		; λοςςελγιρ R5<--αδςεσ ποσμεδξ. βακτα στςολι
		DEC	R5
	AGAIN:
	;----------------------------------------------------------------------
	;  SKANER οπςεδεμρετ πςιξαδμεφξοστψ σινχομα (R3) λ λμΰώαν.δμρ λμΰώεχοηο
	;	  B R0 σνεύεξιε εηο χ  στςολε KEY υνξοφεξξοε ξα 2
	;	!!!!! R3 ξα χωθοδε υλαϊωχαετ ξα σμεδυΰύικ  σινχOμ  !!!!!!
	;----------------------------------------------------------------------
	;SKANER
		TRAP	112
		CMP	R3,R5		; λοξεγ οβςαβοτλι ποδστςολι?
		BHI	NEXT		; δα
		CLR	R0		; πεςχοξαώαμψξο  ξυμεχοε σνεύεξιε
	1$:	CMPB	KEY(R0),(R3)	; σινχομω σθοδρτσρ
		BEQ	2$		; δα-ξα χωθοδ
		INC	R0		; ξετ--σμεδυΰύικ
		TSTB	KEY(R0)		; ξυμεχοκ ? δα-ξα χωθοδ
		BNE	1$		; ξετ--οπρτψ σςαχξεξιε
		BR	ERROR		; ξε λμΰώ
	2$:	ASL	R0		;  * 2
		INC	R3		; πςοδχιφεξιε R3
	;----------------------------------------------------------
	;	SELEKTOR οσυύεστχμρετ χετχμεξιε πο οβςαβοτλε λμΰώεκ
	;----------------------------------------------------------
	;SELEKTOR
		CMP	R0,#16		; πεςενεύεξιε  RLDUEFGH
		BLT	3$		; ξετ
		JMP	RDEG$		; δα--ξα RDEG$
	3$:	JMP	@CASE(R0)	; ξετ---χετχμεξιE
	;
	KEY:

		.ASCIZ	/MNBCSAXRULDRULEHGFEHG/		; λμΰώι
		.EVEN
	CASE:
		.WORD	M$,N$,B$,C$,S$,A$,X$		;νετλι πεςεXοδα SELEKTOR
	;
	NEXT:				; οβςαβοτλα σμεδ. ποδστςολι
		POP	<R0,R5,R3>	; ώτεξιε WM,αδς.ι δμ. στςολι
		PUSH	R0		; ϊαπισψ WM
		BR	NEWSTR
	;------------------------------
	;	X$---οβςαβοτλα ποδστςολ
	;------------------------------
	X$:
		POP	R0		; σοθςαξιτψ WM
		CMP	-(SP),-(SP)	; ϊαςεϊεςχιςοχατψ 2 σμοχα
		CALL	BLNC		; πςοπυσλ πςοβεμοχ
		CALL	$STRNG		; πομυώεξιε χ στελε αδςεσα ξοχοκ ποδστςολι
					;   ι εε δμιξω. R3 αχτονατιώεσλι πςοδχιξυτ
		CALL	BLNC		; πςοπυσλ πςοβεμοχ
		BNE	ERROR		; οηςαξιώιτεμψ-";" ? ξετ-οϋιβλα
		INC	R3		; πςοπυσλ ";"
		SUB	R3,R5		; λοςςελγιρ R5<--δμιξα στςολι
		INC	R5
		MOV	R3,6(SP)	; ϊαπισψ χ οτλμαδωχαενωθ
		MOV	R5,4(SP)	;    αδςεσα ι  δμιξω
		POP	<R5,R3> 	; πομυώεξιε ξοχωθ
		PUSH	R0		; χοσστ. WM
		BR	NEWSTR
	;
	ERROR:				; οϋιβλα
		TRAP	5
	;
	BLNC:	TRAP	112		;πςοπυσλ πςοβεμοχ
		CMP	R3,R5
		BHI	ERROR
		CMPB	#';,@R3
		RETURN
	;
	OUT:	CMP	(SP)+,(SP)+	; οώιστλα στελα WM
		POP	<R5>		; χοσστ. R5
	RET:	CLR	SAVJMP
		JMP	@(R4)+		; !!!!!!!!! χωθοδ ιϊ $DRAW
	;
	;-----------------------------------------
	;		οβςαβοτλα οτδεμψξωθ λοναξδ
	;-----------------------------------------
	B$:				; λον. B--"ποδξρτοε πεςο"
		BIS	#4000,(SP)	; υσταξοχλα βιτα 11 χ σμοχε πεςενεύ.
		BR	AGAIN
	;
	N$:				; λον. N--χοϊχςατ λ ξυμΰ
		BIS	#100000,(SP)	; υσταξοχλα βιτα 15-πςιϊξαλ χοϊχςατα λ τώ.(0,0)
		BR	AGAIN
	;
	S$:				; λον. S--υσταξοχλα νασϋταβξ.λοεζζ.
		CLR	R0
		CALL	$$SENSE		; ώτεξιε ϊξαώεξιρ

		BNE	1$
		MOV	#4,R0		; ξυμεχοκ νασϋταβ--υνομώαξιε
	1$:	MOVB	R0,$SCRT	; ϊασωμλα χ σμοχο χςαύεξιρ-νασϋτ.
		BR	AGAIN
	;
	C$:				; λον. C--υσταξοχλα γχετα
		CLR	R0		; υνομώαξιε
		CALL	$$SENSE		; ώτεξιε
		TST	R0
		BNE	1$
		MOV	PAPER,R0
	1$:	CMP	#10,R0		; R0<=8
		BLO	ERROR		; ξετ-οϋιβλα
		PUSH	<R1>
		MOV	R0,R1		; R2   =  λοδω γχετοχ:   λςασξωκ  5
					;			 ϊεμεξωκ  3
					;			 σιξικ    2
					;			 ώεςξωκ   1 ι τ.δ.
		CALL	COLSET		; πεςεδαώα λοδα χ δςακχες
		POP	<R1>
		BR	AGAIN
	;
	A$:				; λον. α--χςαύεξιε οσεκ
		CLR	R0		; υνομώαξιε
		CALL	$$SENSE		; πομυώεξιε ϊξαώεξιρ
		CMP	R0,#4		; πςοχεςλα ηςαξιγ
		BHIS	ERROR
		MOVB	R0,$SCRT+1	; υσταξοχλα ξοχοηο ϊξαώεξιρ χςαύεξιρ
	JAG:	BR	AGAIN
	;----------------------------------------
	;		χθοδ δμρ οβςαβοτλι λον. M
	;----------------------------------------
	M$:
		PUSH	<R1,R2>		; σοθςαξεξιε λοοςδιξατ
		CALL	$$SIGN		; πομυώεξιε ϊξαλα
		CLR	R0		; υνομώαξιε
		CALL	$$SENSE		; πομυώεξιε ϊξαώεξιρ
		BIT	#1000,4(SP)	; οτξοσιτεμψξοε ?
		BEQ	1$		; ξετ
		CALL	$$SCALE		; δα--νασϋταβιςοχαξιε
	1$:	MOV	R0,R1		; λοοςδιξατα θ
		CALL	BLNC		; πςοπυσλ πςοβεμοχ
		CMPB	#',,(R3)	; "," ?
		BNE	ERROR		; ξετ--οϋιβλα
		INC	R3		; πςοπυσλ ","
		ASLB	4(SP)		; χ WM βιτ 1--X,βιτ 0--Y
		ASRB	5(SP)		; σοθς. πςιϊξαλα οτξοσιτ.
		CALL	$$SIGN		; πομυώεξιε ϊξαλα Y
		CLR	R0		; υνομώαξιε
		CALL	$$SENSE		; πομυώεξιε ϊξαώεξιρ  Y
		ASLB	5(SP)		; χοσσταξ. πςιϊξ. οτξοσιτ.
		BIT	#1000,4(SP)	; οτξοσιτεμψξοε ?
		BEQ	2$		; ξετ
		CALL	$$SCALE		; δα--νασϋταβιςοχαξιε
	2$:	MOV	R0,R2		; σνεύεξιε πο Y
		CMP	(SP)+,(SP)+	; υλαϊατεμψ στελα ξα WM
		BIT	#1000,(SP)	; οτξοσιτεμψξοε ?

		BEQ	MOVIN		; ξετ- αβσομΰτ.
	;*******	οτξοσιτεμψξοε
		MOVB	$SCRT+1,R0	; βακτ χςαύεξιρ
		CMP	#2,R0		; α0 ιμι α1
		BGT	5$		; δα
		NEG	R2		; ξετ--ιϊνεξεξιε ϊξαλα δY
	5$:	DEC	R0
		CMP	#2,R0		; α1 ιμι α2
		BLOS	6$
		NEG	R1		; δα-ιϊνεξεξιε ϊξαλα δθ
	6$:	ASRB	(SP)		; ϊξαλ "-" πςι δY ?
		BCC	7$		; ξετ
		NEG	R2		; δα-ιϊνεξεξιε ϊξαλα δY
	7$:	ASRB	(SP)		; ϊξαλ "-" πςι δθ ?
		BCC	8$		; ξετ
		NEG	R1		; δα--ιϊνεξεξιε ϊξαλα δθ
	8$:	ASR	R0		; α0 ιμι α2
		BCS	9$		; δα
		MOV	R1,R0		; ξετ-πεςεσταξοχλα
		MOV	R2,R1
		MOV	R0,R2
	9$:	ADD	-2(SP),R1	; πςιβαχμεξιε λοοςδιξατ
		ADD	-4(SP),R2	; πςιβαχμεξιε λοοςδιξατ
		BR	MOVIN		; πεςεθοδ ξα πεςενεύεξιε
	;-------------------------------------------------------------
	;			χθοδ  οβςαβοτλι λον.   R,L,D,U,E,F,G,H
	;-------------------------------------------------------------
	;		R U  L D  R U  L E  H  G  F  E  H  G
	COD:	.BYTE	2,10,3,11,2,10,3,12,17,13,16,12,17,13
	;-------------------------------------------------------------
	RDEG$:
		SUB	#16,R0		; λοςςελγιρ σνεύεξιρ
		ASR	R0		; -----"----"---
		PUSH	R0		; οσχοβοδιτψ R0 ,σοθςαξιχ χ στελε
		MOVB	$SCRT+1,R0	; βακτ χςαύεξιρ ιϊ $SCRT--> χ R0
		ADD	(SP)+,R0	; σμοφεξιε σνεύεξιρ ι βακτα χςαύεξιρ χ R0
		MOVB	COD(R0),(SP)	; ϊασματψ λοδ χ σμοχο πεςενεύεξικ
		MOV	#1,R0		; υνομώαξιε
		CALL	$$SENSE		; πομυώιτψ ϊξαώεξιε
		CALL	$$SCALE		; νασϋταβιςοχαξιε
		ASRB	(SP)		; βιτ 0-- οτςιγατεμψξωκ R0 ?
		BCC	1$		; δα --ιϊνεξεξιε ϊξαλα
		NEG	R0		; -R0
	1$:	ASRB	(SP)		; βιτ 1--σνεύεξιε πο θ
		BCC	2$		; ξετ
		ADD	R0,R1		; σνεύεξιε πο  θ
	2$:	ASRB	(SP)		; βιτ 2-- ιϊνεξεξιε ϊξαλα R0 ?
		BCC	3$		; ξετ
		NEG	R0		; ιϊνεξεξιε ϊξαλα
	3$:	ASRB	(SP)		; βιτ 3-- σνεύεξιε πο Y
		BCC	MOVIN		; ξετ -πεςεθοδ ξα πεςενεύεξιε
		ADD	R0,R2		; σνεύεξιε πο Y
	;----------------------------------
	;			πεςενεύεξιρ
	;----------------------------------
	MOVIN:
		ASRB	@SP		; δμρ αβσομΰτξοηο M

		BCC	5$		; Y σο ϊξαλον "-" ?
		NEG	R2		; δα
	;
	5$:	PUSH	<R1,R2>
		CALL	GXYRD
		MOV	R1,-(SP)
		MOV	R2,-(SP)
		MOV	4(SP),R2
		MOV	6(SP),R1
		MOV	(SP)+,2(SP)
		MOV	(SP)+,2(SP)
		BIT	#4000,4(SP)	; 11-βιτ:ςισοχαξιε (0)--πεςενεύεξιε (1)
		BNE	1$		; πεςενεύεξιε
		CALL	GLNTST		; χελτος
		BR	2$
	1$:	CALL	GXYST		; πεςενεύεξιε--τοώλα
	2$:	TST	4(SP)		; χοϊχςατ λ πςεφξιν λοοςδιξαταν?
		BPL	3$		; ξετ
		MOV	(SP)+,R2	; δα- χοσσταξοχμεξιε λοοςδιξατ
		MOV	(SP)+,R1
		CALL	GXYST
		BR	4$
	3$:	CMP	(SP)+,(SP)+
	4$:	MOV	#70000,(SP)
		JMP	AGAIN
	;-----------------------------------------
	;		πομυώεξιε ϊξαKα δμρ λον. ν
	;-----------------------------------------
	$$SIGN:
		CALL	BLNC		; πςοπυσλ πςοβεμοχ
		CMPB	#'+,(R3)	; πμΰσ ?
		BNE	1$		; ξετ
		BIS	#1000,6(SP)	; δα--υσταξοχλα βιτα 9
		BIC	#1,6(SP)	; Cβςοσ βιτα 0
		INC	R3		; πςοπυσλ "+"
		BR	2$
	1$:	CMPB	#'-,(R3)	; νιξυσ ?
		BNE	2$		; ξετ
		BIS	#1001,6(SP)	; δα--υσταξοχλα βιτοχ 0 ι 9
		INC	R3		; πςοπυσλ "-"
	2$:	RETURN
	;------------------------------------------------------------------
	;		πςοηςαννα $$SCALE  λοςςελτιςυετ R0 χ σοοτχετστχιι σ
	;		νασϋταβον, τ.ε. δεμιτ ξα 4 ι υνξοφαετ ξα νασϋταβξωκ
	;		λοόζζιγιεξτ,λοτοςωκ θςαξιτσρ χ νμαδϋεν βακτε $SCRT
	;------------------------------------------------------------------
	$$SCALE:
		PUSH	<R1,R2,R3>	; οσχοβοδιτψ R1,R2,R3 Dμρ υνξοφεξιρ
		MOV	#8.,R2		; ώισμο ςαϊςρδοχ-ώισμο σμοφεξικ
		CLR	R1		; ξαλοπιτεμψ πςοιϊχεδεξιρ
		MOVB	$SCRT,R3	; νξοφιτεμψ
	1$:	ROR	R3		; ςαϊςρδ νξοφιτεμρ χ βιτ σ
		BCC	2$		; ξομψ
		ADD	R0,R1		; εδιξιγα--σμοφεξιε
	2$:	CMP	R2,#7		; δμρ ςαϊςρδοχ 0 ι 1
		BLT	3$
		ASR	R1		; σδχιη πςοιϊχεδεξιρ (δεμεξιε ξα 4)

		BR	4$
	3$:	ASL	R0		; δμρ οσταμψξωθ-σδχιη νξοφιτεμρ
	4$:
		SOB	R2,1$		; χσε ςαϊςρδω ?
		MOV	R1,R0		; ςεϊυμψτατ -χ R0
		POP	<R3,R2,R1>	; χοσσταξοχιτψ R1 ι R2
		RETURN
	;-------------------------------------------------------------------
	;		πςοηςαννα $$SENSE χοϊχςαύαετ χ R0 ϊξαώεξιε λοξσταξτω
	;		ιμι πεςενεξξοκ (λοξστςυλγιι =<ινρ> )
	;-------------------------------------------------------------------
	$$SENSE:
		TRAP	112		; πςοπυσλ πςοβεμοχ
		CMPB	@R3,#';
		BNE	1$
		INC	R3		; πςοπυσλ ";"
	6$:	RETURN
	1$:	CMP	R3,R5
		BHI	6$
		CMPB	#'=,(R3)	; λοξστςυλγιρ =<ινρ>
		BNE	2$		; ξετ-λοξσταξτα
		INC	R3		; πςοπυσλ "="
		CALL	BLNC		; πςοπυσλ πςοβεμοχ
		CALL	$VALUE		; ώτεξιε ϊξαώεξιρ χ στελ
		CALL	BLNC		; πςοπυσλ πςοβεμοχ
		BEQ	3$		; οηςαξιώιτεμψ- ";" ? δα
		JMP	ERROR		; οϋιβλα
	2$:
		CMPB	#'9,(R3)	; γιζςα ?
		BLO	5$
		CMPB	#'0,(R3)
		BHI	5$
		CALL	$CONST		; ώτεξιε λοξσταξτω
		CALL	BLNC		; πςοπυσλ πςοβεμοχ
		BNE	4$		; ξετ ";"
	3$:	INC	R3		; πςοπυσλ ";"
	4$:
		POP	<R0>
	;
	5$:	RETURN
	;
	;
		.END

                                                                                                                                                                                                                                                                        