	.ASECT
	.=000100
	.ASCII	/****************/
	.ASCII	/                /
	.ASCII	/    Hacked by   /
	.ASCII	/   O l e g  H.  /
	.ASCII	/   25. 10. 91.  /
	.ASCII	/                /
	.ASCII	/****************/
	.=000300
	.ASCII	/Corrected by LDN/
	.ASCII	/August 1993/
	.=000400
	.ASCII	/Внимание !!!    /
	.ASCII	/Программа выводит текстовые сообщения в коде КОИ-8, /
	.ASCII	/поэтому вы должны иметь драйвер, обслуживающий терминал в КОИ-8./
	.ASCII	/ (например, мой TS.SYS для УКНЦ).                /
	.ASCII	/Олег Ховайко, (UB5AJV).   /<000>
	.ASCII	<000><000><033><110><033><112><052>
	.ASCII	/BASED ON '/<016>/PIKNIK NA OBO^INE/<017>/'* /

	.PSECT
